"use client"

import type React from "react"

import { useRef, useState, useEffect, useMemo, useCallback } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Upload, Play, Pause, Camera, Zap, Trash2, AlertCircle } from "lucide-react"
import { WorkLogItem } from "@/components/work-log-item"
import { AIAnalysisStatus } from "@/components/ai-analysis-status"
import { AudioPermissionManager } from "@/components/audio-permission-manager"
import { useScreenCapture } from "@/hooks/use-screen-capture"
import { cn } from "@/lib/utils"

interface DistractionCheck {
  is_distracted: boolean
  reason: string
  planned_task: string
  severity: "high" | "medium" | "low"
}

interface ReportData {
  summary: string
  productivity_analysis: string
  focus_trend: string
  distraction_summary: string
  time_distribution: {
    productive_time: number
    distracted_time: number
    neutral_time: number
  }
  key_findings: string[]
  recommendations: string[]
  overall_score: number
}

interface WorkLogEntry {
  id: string
  timestamp: Date
  activity: string
  category: "productive" | "distracted" | "neutral"
  details: string
  screenshot_url?: string
  confidence?: number
  applications?: string[]
  focus_score?: number
  distraction_check?: DistractionCheck
  report_type?: string
  report_data?: ReportData
}

interface WorkLogPanelProps {
  currentTask: string
  apiKey: string
  model: string
  captureInterval: number
  workLogs: WorkLogEntry[]
  addWorkLog: (log: any) => Promise<any>
  clearWorkLogs: () => Promise<void>
}

export function WorkLogPanel({
  currentTask,
  apiKey,
  model,
  captureInterval,
  workLogs,
  addWorkLog,
  clearWorkLogs,
}: WorkLogPanelProps) {
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [isApiKeyValid, setIsApiKeyValid] = useState(false)
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [isOcrLoading, setIsOcrLoading] = useState(false)
  const prevImageDataRef = useRef<ImageData | null>(null)
  const tesseractWorkerRef = useRef<any>(null)

  // Tesseract workerの初期化（初回のみ）
  const getOcrWorker = useCallback(async () => {
    if (tesseractWorkerRef.current) return tesseractWorkerRef.current
    setIsOcrLoading(true)
    try {
      const { createWorker } = await import("tesseract.js")
      const worker = await createWorker(["jpn", "eng"])
      tesseractWorkerRef.current = worker
      return worker
    } finally {
      setIsOcrLoading(false)
    }
  }, [])

  // アンマウント時にworkerを解放
  useEffect(() => {
    return () => {
      tesseractWorkerRef.current?.terminate()
    }
  }, [])

  const getImageData = useCallback(async (blob: Blob): Promise<ImageData> => {
    return new Promise((resolve) => {
      const img = new Image()
      const url = URL.createObjectURL(blob)
      img.onload = () => {
        const canvas = document.createElement("canvas")
        canvas.width = 64
        canvas.height = 36
        const ctx = canvas.getContext("2d")!
        ctx.drawImage(img, 0, 0, 64, 36)
        resolve(ctx.getImageData(0, 0, 64, 36))
        URL.revokeObjectURL(url)
      }
      img.src = url
    })
  }, [])

  const calculateDiff = useCallback((a: ImageData, b: ImageData): number => {
    let diff = 0
    for (let i = 0; i < a.data.length; i += 4) {
      diff += Math.abs(a.data[i] - b.data[i])
      diff += Math.abs(a.data[i + 1] - b.data[i + 1])
      diff += Math.abs(a.data[i + 2] - b.data[i + 2])
    }
    return diff / ((a.data.length / 4) * 3 * 255)
  }, [])

  const logCountRef = useRef(0)
  const hasAutoGeneratedRef = useRef(new Set<string>())

  useEffect(() => {
    const isValid = Boolean(apiKey && apiKey.trim().length > 0)
    setIsApiKeyValid(isValid)
  }, [apiKey])

  useEffect(() => {
    const regularLogs = workLogs.filter((log) => !log.report_type)
    const newLogCount = regularLogs.length

    // 3件ごとにレポート生成（重複を防ぐ）
    if (newLogCount > 0 && newLogCount % 3 === 0 && newLogCount > logCountRef.current) {
      const reportKey = `report-${newLogCount}`

      if (!hasAutoGeneratedRef.current.has(reportKey)) {
        console.log("📊 Auto-generating report after 3 new logs...")
        hasAutoGeneratedRef.current.add(reportKey)
        logCountRef.current = newLogCount
        handleAutoGenerateReport(regularLogs)
      }
    }
  }, [workLogs.length]) // 依存配列を workLogs.length のみにして安定化

  const analyzeScreenshot = useCallback(
    async (blob: Blob) => {
      if (!apiKey) {
        console.error("❌ API key not available")
        return
      }

      setIsAnalyzing(true)

      try {
        // 前回と画面が変わっていなければAPIをスキップ（閾値3%）
        const currentImageData = await getImageData(blob)
        if (prevImageDataRef.current) {
          const diff = calculateDiff(prevImageDataRef.current, currentImageData)
          if (diff < 0.03) {
            console.log(`[v0] Screen unchanged (diff=${(diff * 100).toFixed(1)}%), skipping API call`)
            setIsAnalyzing(false)
            return
          }
          console.log(`[v0] Screen changed (diff=${(diff * 100).toFixed(1)}%), calling API`)
        }
        prevImageDataRef.current = currentImageData

        // ブラウザ側でOCR実行（Gemini API不要）
        console.log("🔍 Running OCR with Tesseract.js...")
        const worker = await getOcrWorker()
        const { data: { text: ocrText } } = await worker.recognize(blob)
        const extractedText = ocrText.trim() || "画面情報を取得できませんでした"
        console.log(`[v0] OCR extracted ${extractedText.length} chars`)

        const formData = new FormData()
        formData.append("extractedText", extractedText)
        formData.append("apiKey", apiKey)
        formData.append("currentTask", currentTask || "作業中")

        console.log("[v0] Sending OCR text to /api/analyze-screenshot")

        const response = await fetch("/api/analyze-screenshot", {
          method: "POST",
          body: formData,
        })

        console.log("[v0] Response status:", response.status)
        console.log("[v0] Response ok:", response.ok)

        if (!response.ok) {
          const errorData = await response.json()
          console.error("[v0] API error response:", errorData)

          if (errorData.error === "quota_exceeded") {
            alert(
              errorData.userMessage || "Gemini APIの利用制限に達しました。しばらく時間をおいてから再試行してください。",
            )
            return
          }

          throw new Error(errorData.message || `API error: ${response.status}`)
        }

        const result = await response.json()
        console.log("[v0] Analysis result:", result)

        if (result.error) {
          throw new Error(result.error)
        }

        const imageUrl = URL.createObjectURL(blob)

        const logEntry = {
          timestamp: new Date().toISOString(),
          activity: result.activity || "不明な活動",
          category: result.category || "neutral",
          details: result.details || "詳細なし",
          screenshot_url: imageUrl,
          confidence: result.confidence || 0,
          applications: result.applications || [],
          focus_score: result.focus_score || 0,
          distraction_check: result.distraction_check || null,
        }

        console.log("[v0] Adding work log entry:", logEntry)

        await addWorkLog(logEntry)

        // 脱線検知時に自動アラート音を再生
        if (result.distraction_check?.is_distracted) {
          console.log("🚨 Distraction detected! Playing alert sound...")
          playAlertSound()
        }

        console.log("✅ Work log added successfully")
      } catch (error) {
        console.error("❌ Analysis error:", error)
        const errorMessage = error instanceof Error ? error.message : "不明なエラー"
        alert(`解析エラー: ${errorMessage}\n\n詳細はコンソールログを確認してください。`)
      } finally {
        setIsAnalyzing(false)
      }
    },
    [apiKey, currentTask, model, addWorkLog, getOcrWorker],
  ) // 必要最小限の依存関係のみ

  const handleAutoGenerateReport = useCallback(
    async (regularLogs: WorkLogEntry[]) => {
      if (!apiKey || regularLogs.length < 3) {
        return
      }

      try {
        console.log("📊 Auto-generating summary report...")

        const response = await fetch("/api/generate-summary-report", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            workLogs: regularLogs.slice(-3), // 最新の3件を使用
            apiKey,
            model: model || "gemini-2.5-flash-lite",
          }),
        })

        if (!response.ok) {
          throw new Error(`API error: ${response.status}`)
        }

        const reportData = await response.json()
        console.log("✅ Report generated:", reportData)

        await addWorkLog({
          timestamp: new Date().toISOString(),
          activity: "作業統合レポート（自動生成）",
          category: "neutral",
          details: reportData.summary,
          report_type: "summary",
          report_data: reportData,
        })

        console.log("✅ Auto-generated report added to logs")
      } catch (error) {
        console.error("❌ Auto report generation error:", error)
      }
    },
    [apiKey, model, addWorkLog],
  ) // 必要最小限の依存関係のみ

  const handleCapture = useCallback(
    (blob: Blob) => {
      console.log("📸 Screenshot captured, starting analysis...")
      analyzeScreenshot(blob)
    },
    [analyzeScreenshot],
  )

  const handleError = useCallback((error: Error) => {
    console.error("❌ Screen capture error:", error)
    alert(`画面キャプチャエラー: ${error.message}`)
  }, [])

  const handleScreenshotUpload = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      if (event.target.files && event.target.files.length > 0) {
        const file = event.target.files[0]
        const reader = new FileReader()

        reader.onload = (e) => {
          if (e.target && e.target.result) {
            const blob = new Blob([e.target.result], { type: file.type })
            analyzeScreenshot(blob)
          }
        }

        reader.readAsArrayBuffer(file)
      }
    },
    [analyzeScreenshot],
  )

  const { isTracking, isCapturing, lastCaptureTime, startAutoCapture, stopCapture } = useScreenCapture({
    interval: captureInterval * 1000,
    quality: 0.8,
    onCapture: handleCapture,
    onError: handleError,
  })

  const handleToggleTracking = async () => {
    if (isTracking) {
      console.log("⏹️ Stopping screen capture...")
      stopCapture()
    } else {
      console.log("▶️ Starting screen capture...")
      await startAutoCapture()
    }
  }

  const playAlertSound = () => {
    try {
      const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)()

      for (let i = 0; i < 2; i++) {
        setTimeout(() => {
          const oscillator = audioContext.createOscillator()
          const gainNode = audioContext.createGain()

          oscillator.connect(gainNode)
          gainNode.connect(audioContext.destination)

          oscillator.frequency.setValueAtTime(800, audioContext.currentTime)
          oscillator.frequency.setValueAtTime(600, audioContext.currentTime + 0.15)

          gainNode.gain.setValueAtTime(0.1, audioContext.currentTime)
          gainNode.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + 0.3)

          oscillator.start(audioContext.currentTime)
          oscillator.stop(audioContext.currentTime + 0.3)
        }, i * 400)
      }
    } catch (error) {
      console.error("❌ Failed to play alert sound:", error)
    }
  }

  const onPlayAlert = () => {
    playAlertSound()
  }

  const onClearLogs = async () => {
    if (confirm("すべての作業ログをクリアしますか？")) {
      await clearWorkLogs()
      logCountRef.current = 0
      hasAutoGeneratedRef.current.clear()
    }
  }

  const stats = useMemo(() => {
    const regularLogs = workLogs.filter((log) => !log.report_type)

    if (regularLogs.length === 0) {
      return {
        averageFocusScore: 0,
        productivePercentage: 0,
      }
    }

    const totalFocusScore = regularLogs.reduce((sum, log) => sum + (log.focus_score || 0), 0)
    const averageFocusScore = totalFocusScore / regularLogs.length

    const productiveLogs = regularLogs.filter((log) => log.category === "productive").length
    const productivePercentage = (productiveLogs / regularLogs.length) * 100

    return {
      averageFocusScore,
      productivePercentage,
    }
  }, [workLogs])

  const regularLogsCount = useMemo(() => workLogs.filter((log) => !log.report_type).length, [workLogs])
  const logsUntilNextReport = useMemo(() => (regularLogsCount > 0 ? 3 - (regularLogsCount % 3) : 3), [regularLogsCount])

  return (
    <div className="space-y-4">
      {/* 音声アラート設定 */}
      <AudioPermissionManager onPermissionGranted={() => console.log("Audio permission granted")} />

      {/* 画面解析コントロール */}
      <Card className="shadow-lg border-0 bg-white/90 backdrop-blur-sm">
        <CardHeader className="pb-3 bg-gradient-to-r from-purple-50 to-pink-50 rounded-t-lg border-b border-gray-100">
          <CardTitle className="flex items-center gap-2 text-gray-800">
            <Camera className="h-5 w-5 text-purple-600" />
            画面解析 + 脱線検知
            <div
              className={cn(
                "w-3 h-3 rounded-full shadow-sm",
                isTracking ? "bg-green-500 animate-pulse" : "bg-gray-400",
              )}
            />
            <Badge variant="outline" className="ml-auto border-purple-200 text-purple-700 bg-purple-50">
              <Zap className="h-3 w-3 mr-1" />
              {captureInterval < 60 ? `${captureInterval}秒間隔` : `${captureInterval / 60}分間隔`}
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {!isApiKeyValid && (
            <div className="p-3 bg-yellow-50 border border-yellow-200 rounded-lg flex items-start gap-2">
              <AlertCircle className="h-4 w-4 text-yellow-600 mt-0.5" />
              <div className="text-sm text-yellow-800">
                <div className="font-medium">⚠️ Gemini APIキーが未設定です</div>
                <div className="text-xs mt-1">
                  画面解析を開始する前に、設定からAPIキーを登録してください。
                  <br />
                  登録後、ページを再読み込みする必要はありません。自動的に反映されます。
                </div>
              </div>
            </div>
          )}

          {isApiKeyValid && (
            <div className="p-3 bg-green-50 border border-green-200 rounded-lg flex items-start gap-2">
              <div className="text-sm text-green-800">
                <div className="font-medium">✅ Gemini API連携完了</div>
                <div className="text-xs mt-1">
                  解析機能が利用可能です。解析開始ボタンをクリックしてください。
                  <br />📊 レポートは3件のログごとに自動生成されます（次回まで残り{logsUntilNextReport}件）
                </div>
              </div>
            </div>
          )}

          {isTracking && lastCaptureTime && (
            <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <div className="text-sm text-blue-800">
                <div className="font-medium">📸 自動キャプチャ実行中</div>
                <div className="text-xs mt-1">
                  最終キャプチャ: {lastCaptureTime.toLocaleTimeString("ja-JP")}
                  <br />
                  次回キャプチャまで: 約{captureInterval < 60 ? `${captureInterval}秒` : `${captureInterval / 60}分`}
                </div>
              </div>
            </div>
          )}

          <div className="flex gap-3 flex-wrap">
            <Button
              onClick={handleToggleTracking}
              variant={isTracking ? "destructive" : "default"}
              disabled={!isApiKeyValid || isCapturing}
              className={cn(
                "flex items-center gap-2 shadow-md transition-all duration-200",
                isTracking
                  ? "bg-red-500 hover:bg-red-600 shadow-red-200"
                  : "bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 shadow-blue-200",
              )}
            >
              {isOcrLoading ? (
                <>
                  <Camera className="h-4 w-4 animate-pulse" />
                  OCR初期化中...
                </>
              ) : isCapturing ? (
                <>
                  <Camera className="h-4 w-4 animate-pulse" />
                  キャプチャ中...
                </>
              ) : isTracking ? (
                <>
                  <Pause className="h-4 w-4" />
                  解析停止
                </>
              ) : (
                <>
                  <Play className="h-4 w-4" />
                  解析開始
                </>
              )}
            </Button>

            <Button
              variant="outline"
              onClick={() => fileInputRef.current?.click()}
              disabled={isAnalyzing || !isApiKeyValid}
              className="flex items-center gap-2 shadow-md border-gray-300 hover:bg-gray-50 transition-all duration-200"
            >
              <Upload className="h-4 w-4" />
              {isAnalyzing ? "解析中..." : "スクリーンショット"}
            </Button>

            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              onChange={handleScreenshotUpload}
              className="hidden"
            />
          </div>

          <div className="text-sm text-gray-600">
            <p>
              💡 <strong>統合解析機能:</strong>
            </p>
            <ul className="list-disc list-inside mt-1 space-y-1 text-xs">
              <li>
                {captureInterval < 60 ? `${captureInterval}秒` : `${captureInterval / 60}分`}
                間隔で自動スクリーンショット
              </li>
              <li>画面解析と脱線判定を同時実行（効率的な処理）</li>
              <li>タイムトラッカーの作業内容と画面内容を自動比較</li>
              <li>脱線検知時に即座に音声アラートで警告</li>
              <li>
                <strong>3件のログごとに統合レポートを自動生成</strong>（レポートタブで確認）
              </li>
              <li>
                <strong>作業内容が未入力でも解析可能</strong>（ただし精度は低下します）
              </li>
            </ul>
          </div>

          {currentTask ? (
            <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <div className="text-sm text-blue-800">
                <div className="font-medium mb-1">🎯 現在の予定作業:</div>
                <div>{currentTask}</div>
                <div className="text-xs mt-1 opacity-75">この内容と画面解析結果を比較して脱線を自動判定します</div>
              </div>
            </div>
          ) : (
            <div className="p-3 bg-gray-50 border border-gray-200 rounded-lg">
              <div className="text-sm text-gray-600">
                ℹ️ <strong>作業内容が未設定です</strong>
                <div className="text-xs mt-1">
                  タイムトラッカーで作業内容を入力すると、より正確な脱線判定が可能になります。
                  <br />
                  未入力でも画面解析は実行されますが、脱線判定の精度が低下します。
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* AI分析サマリー */}
      <AIAnalysisStatus
        totalLogs={regularLogsCount}
        averageFocusScore={stats.averageFocusScore}
        productivePercentage={stats.productivePercentage}
        isAnalyzing={isAnalyzing}
      />

      {/* 作業ログ一覧 */}
      <Card className="flex-1 shadow-lg border-0 bg-white/90 backdrop-blur-sm">
        <CardHeader className="pb-3 bg-gradient-to-r from-gray-50 to-slate-50 rounded-t-lg border-b border-gray-100">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-gray-800">
              作業ログ
              <Badge variant="secondary" className="bg-blue-100 text-blue-700 border-blue-200">
                {regularLogsCount}件
              </Badge>
              {isAnalyzing && (
                <Badge variant="outline" className="animate-pulse border-orange-200 text-orange-700 bg-orange-50">
                  解析中...
                </Badge>
              )}
            </CardTitle>
            {workLogs.length > 0 && (
              <Button
                variant="outline"
                size="sm"
                onClick={onClearLogs}
                className="flex items-center gap-2 text-red-600 hover:text-red-700 border-red-200 hover:bg-red-50 transition-all duration-200 bg-transparent"
              >
                <Trash2 className="h-4 w-4" />
                全てクリア
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <ScrollArea className="h-[600px] px-6">
            <div className="space-y-4 pb-4">
              {workLogs
                .filter((log) => !log.report_type)
                .map((log) => (
                  <WorkLogItem key={log.id} log={log} onPlayAlert={onPlayAlert} />
                ))}
              {regularLogsCount === 0 && (
                <div className="text-center py-8 text-gray-500">
                  まだ作業ログがありません。
                  <br />
                  「解析開始」または「スクリーンショット」でログを生成してください。
                </div>
              )}
            </div>
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  )
}
